name: get_stacked
description: An implementation of the Stacked package using Get.
version: 1.0.1
homepage: https://github.com/Prn-Ice/get_stacked

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: ^3.2.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: